parameters:
    app.services.http_code.400: 400
    app.services.http_code.200: 200
    app.services.serialization.format: 'json'

services:
    app.services.transformer.error_response:
        class: App\Common\Transformer\Response\ViolationResponse\ViolationListResponseTransformer
        arguments:
            - '@app.services.transformer.error_response.transformer'
            - '@app.services.transformer.error_response.naming_strategy'

    app.services.transformer.error_response.naming_strategy:
        class: JMS\Serializer\Naming\CamelCaseNamingStrategy

    app.services.transformer.error_response.transformer:
        class: App\Common\Transformer\Response\ResponseTransformer
        arguments:
            - '@app.services.transformer.error_response.builder'
            - '@jms_serializer.serializer'
            - '%app.services.serialization.format%'

    app.services.transformer.error_response.builder:
        class: App\Common\Transformer\Response\Builder\JsonResponseBuilder
        arguments:
            - '%app.services.http_code.400%'
            - []

    app.services.object_copier:
        class: App\Common\ObjectCopier\ObjectCopier
        arguments:
            - '@jms_serializer.serializer'


