version: '3.2'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.nginx
    depends_on:
      - php
    volumes:
      - ./api/public:/usr/src/api/public:ro
    ports:
      - 8080:80

  php:
    build:
      context: ./api
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/api:rw,cached

  client:
    container_name: credit-client
    build:
      context: ./client
    ports:
      - 80:8080

volumes:
  credit-db-data: {}
